### ISSUE TITLE
[Revamp] Add Spanish synonyms 

### ISSUE THREAD

**Issue by kishtarn555** [kishtarn555/rekarel-core#14]
```
import rekarel.spanish;

class program {

  program() {
    si (orientadoAlNorte) {
      avanza();
    }
    repetir (5) {
      dejaZumbador();
    }
  }
}

```

# Advantages
* Allows for deprecation of pascal (which)
* Enables spanish readers to read java syntax more easily

# Disadvantages
* For non spanish speakers (which atm there aren't many if at all), it may cause alienation
* Codes will sometimes be in English, sometimes be in Spanish

**Comment by ccepeda** [comment]
I don't believe it will add value to Karel. People that use java-language are used to English commands, and adding Spanish synonyms won't make the code fully readable in Spanish because of language reserved words (if, for, etc). So it doesn't add value for java coders and doesn't replace pascal coders.
